In [6]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

import os 
os.getcwd()

'/home/selezov_su/notebooks/Promics/Panoram'

In [7]:
import requests


def call_string(request_url, params):
    return requests.post(request_url, data=params)


def main(
        prot_list,
        string_api_url="https://version-11-5.string-db.org/api",
        method='interaction_partners?',
        output_format = "tsv",
        network_type="functional",
        # add_nodes=10,
    ):

    request_url = "/".join([string_api_url, output_format, method])

    params = {
        "identifiers" : "%0d".join(prot_list),     # your protein
        "species" : 9606,                          # species NCBI identifier 
        "caller_identity" : "www.awesome_app.org", # your app name
        "required_score" : "100",    
        "limit" : 15,
        # threshold of significance
    }

    resp =  call_string(request_url, params).text
    
    tab = pd.DataFrame([line.split("\t") for line in resp.split("\n")])
    tab.columns = tab.iloc[0, :]
    tab = tab.iloc[1:, :]
    
    return tab

In [8]:
with open("Data/whole_protein_set.txt", "r") as file:
    proteins = file.read().splitlines() 


resp = main(proteins).iloc[:-1]
resp.loc[resp.escore.astype(float) > 0.1]

,stringId_A,stringId_B,preferredName_A,preferredName_B,ncbiTaxonId,score,nscore,fscore,pscore,ascore,escore,dscore,tscore
16,9606.ENSP00000216336,9606.ENSP00000450540,CTSG,ENSP00000450540,9606,0.962,0,0,0,0,0.247,0,0.952
18,9606.ENSP00000216336,9606.ENSP00000343445,CTSG,SERPINB4,9606,0.958,0,0,0,0,0.33,0.8,0.718
19,9606.ENSP00000216336,9606.ENSP00000355627,CTSG,AGT,9606,0.954,0,0,0,0,0.277,0.9,0.419
22,9606.ENSP00000216336,9606.ENSP00000370473,CTSG,IGFBP3,9606,0.929,0,0,0,0,0.213,0.9,0.174
27,9606.ENSP00000216336,9606.ENSP00000484343,CTSG,SERPINB6,9606,0.911,0,0,0,0,0.12,0.8,0.536
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1158,9606.ENSP00000466090,9606.ENSP00000225275,ELANE,MPO,9606,0.971,0,0,0,0.784,0.141,0,0.859
1160,9606.ENSP00000466090,9606.ENSP00000323929,ELANE,A2M,9606,0.967,0,0,0,0.053,0.134,0,0.963
1163,9606.ENSP00000466090,9606.ENSP00000223642,ELANE,C5,9606,0.932,0,0,0,0.049,0.134,0.9,0.273
1166,9606.ENSP00000466090,9606.ENSP00000370115,ELANE,SERPINB1,9606,0.901,0,0,0,0.065,0.33,0,0.855
1167,9606.ENSP00000466090,9606.ENSP00000351807,ELANE,ELN,9606,0.894,0,0,0,0,0.213,0,0.871

In [4]:
resp#[["score", "nscore", "fscore", "pscore", "ascore", "escore", "dscore", "tscore"]]

,stringId_A,stringId_B,preferredName_A,preferredName_B,ncbiTaxonId,score,nscore,fscore,pscore,ascore,escore,dscore,tscore
1,9606.ENSP00000271835,9606.ENSP00000298295,CRNN,C10orf10,9606,0.934,0,0,0,0,0,0,0.934
2,9606.ENSP00000271835,9606.ENSP00000330391,CRNN,SPRR3,9606,0.715,0,0,0,0.379,0,0,0.56
3,9606.ENSP00000271835,9606.ENSP00000475216,CRNN,KPRP,9606,0.689,0,0,0,0.186,0,0,0.634
4,9606.ENSP00000271835,9606.ENSP00000357779,CRNN,CRCT1,9606,0.642,0,0,0,0.307,0,0,0.505
5,9606.ENSP00000271835,9606.ENSP00000334644,CRNN,LCE3C,9606,0.64,0,0,0,0.069,0,0,0.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,9606.ENSP00000479606,9606.ENSP00000327694,CLTC,AP2A2,9606,0.989,0,0,0,0.239,0.707,0.9,0.598
297,9606.ENSP00000479606,9606.ENSP00000336747,CLTC,HIP1,9606,0.987,0,0,0,0.063,0.898,0.8,0.432
298,9606.ENSP00000479606,9606.ENSP00000377148,CLTC,AP1G1,9606,0.98,0,0,0,0.247,0.831,0.6,0.667
299,9606.ENSP00000479606,9606.ENSP00000360798,CLTC,EPS15,9606,0.979,0,0,0,0.183,0.717,0.6,0.802
300,9606.ENSP00000479606,9606.ENSP00000253083,CLTC,HIP1R,9606,0.979,0,0,0,0.063,0.752,0.6,0.808

In [10]:
import networkx as nx
from pyvis.network import Network


# Create directed graph with networkx
G = nx.DiGraph()
G = nx.from_pandas_edgelist(
    resp.loc[resp.escore.astype(float) > 0.1], 
    source="preferredName_A", 
    target="preferredName_B", 
    edge_attr=["score", "nscore", "fscore"],
)

# Plot with pyvis
net = Network(
    cdn_resources='remote',
    notebook=True,
    directed = True,
    select_menu = True, # Show part 1 in the plot (optional)
    filter_menu = True, # Show part 2 in the plot (optional)
)
net.show_buttons() # Show part 3 in the plot (optional)
net.from_nx(G) # Create directly from nx graph
net.show('test.html')

test.html